---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ryanj-quarkus-app-dev
  namespace: janus-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: janus
  source:
    repoURL: https://github.com/rosa916-rvhvd/quarkus-test-gitops
    targetRevision: HEAD
    path: ./helm/app
    helm:
      parameters:
      - name: namespace.name
        value: ryanj-quarkus-app-dev
      - name: environment
        value: dev
      - name: image.tag
        value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: ryanj-quarkus-app-dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
