---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj-quarkus-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/quarkus-test-gitops